"""Static sensors for Sigenergy."""
from __future__ import annotations

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.const import (
    EntityCategory,
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)
from .common import (SigenergySensorEntityDescription)

class StaticSensors:
    # PV string sensor descriptions
    PV_STRING_SENSORS = [
        SigenergySensorEntityDescription(
            key="voltage",
            name="Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            suggested_display_precision=3,
        ),
        SigenergySensorEntityDescription(
            key="current",
            name="Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            state_class=SensorStateClass.MEASUREMENT,
            suggested_display_precision=3,
        ),
    ]

    PLANT_SENSORS = [
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_status",
            name="Grid Sensor Status",
            icon="mdi:power-plug",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_active_power",
            name="Grid Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            suggested_display_precision=3,
            icon="mdi:transmission-tower",
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_reactive_power",
            name="Grid Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_on_off_grid_status",
            name="Grid Connection Status",
            icon="mdi:transmission-tower-off",
        ),
        # Max power metrics
        SigenergySensorEntityDescription(
            key="plant_max_active_power",
            name="Max Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_max_apparent_power",
            name="Max Apparent Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_soc",
            name="Battery State of Charge",
            device_class=SensorDeviceClass.BATTERY,
            native_unit_of_measurement=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:battery",
        ),
        SigenergySensorEntityDescription(
            key="plant_phase_a_active_power",
            name="Phase A Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_phase_b_active_power",
            name="Phase B Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_phase_c_active_power",
            name="Phase C Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Phase-specific reactive power
        SigenergySensorEntityDescription(
            key="plant_phase_a_reactive_power",
            name="Phase A Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_phase_b_reactive_power",
            name="Phase B Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_phase_c_reactive_power",
            name="Phase C Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Alarm registers
        SigenergySensorEntityDescription(
            key="plant_general_alarm1",
            name="General Alarm 1",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="plant_general_alarm2",
            name="General Alarm 2",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="plant_general_alarm3",
            name="General Alarm 3",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="plant_general_alarm4",
            name="General Alarm 4",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="plant_general_alarm5",
            name="General Alarm 5",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="plant_active_power",
            name="Plant Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:power-plug-battery-outline"
        ),
        SigenergySensorEntityDescription(
            key="plant_reactive_power",
            name="Plant Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_photovoltaic_power",
            name="PV Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            suggested_display_precision=3,
            icon="mdi:solar-power",
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_power",
            name="Battery Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:battery-charging-100",
        ),
        SigenergySensorEntityDescription(
            key="plant_available_max_active_power",
            name="Available Max Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_available_min_active_power",
            name="Available Min Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_available_max_reactive_power",
            name="Available Max Reactive Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_available_min_reactive_power",
            name="Available Min Reactive Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_available_max_charging_power",
            name="Available Max Charging Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_available_max_discharging_power",
            name="Available Max Discharging Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_running_state",
            name="Plant Running State",
            icon="mdi:power",
        ),
        # Grid sensor phase-specific metrics
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_phase_a_active_power",
            name="Grid Phase A Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_phase_b_active_power",
            name="Grid Phase B Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_phase_c_active_power",
            name="Grid Phase C Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_phase_a_reactive_power",
            name="Grid Phase A Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_phase_b_reactive_power",
            name="Grid Phase B Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_grid_sensor_phase_c_reactive_power",
            name="Grid Phase C Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # ESS rated power metrics
        SigenergySensorEntityDescription(
            key="plant_ess_rated_charging_power",
            name="ESS Rated Charging Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_rated_discharging_power",
            name="ESS Rated Discharging Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_available_max_charging_capacity",
            name="Available Max Charging Capacity",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_available_max_discharging_capacity",
            name="Available Max Discharging Capacity",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_rated_energy_capacity",
            name="Rated Energy Capacity",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_charge_cut_off_soc",
            name="Charge Cut-Off SOC",
            native_unit_of_measurement=PERCENTAGE,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_discharge_cut_off_soc",
            name="Discharge Cut-Off SOC",
            native_unit_of_measurement=PERCENTAGE,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="plant_ess_soh",
            name="Battery State of Health",
            native_unit_of_measurement=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:battery-heart",
        ),
    ]

    INVERTER_SENSORS = [
        # Power ratings
        SigenergySensorEntityDescription(
            key="inverter_model_type",
            name="Model Type",
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:information-box"
        ),
        SigenergySensorEntityDescription(
            key="inverter_serial_number",
            name="Serial Number",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
            icon="mdi:information-outline"
        ),
        SigenergySensorEntityDescription(
            key="inverter_machine_firmware_version",
            name="Firmware Version",
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:information-outline"
        ),
        SigenergySensorEntityDescription(
            key="inverter_rated_active_power",
            name="Rated Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_max_apparent_power",
            name="Max Apparent Power",
            native_unit_of_measurement="kVA",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_max_active_power",
            name="Max Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_max_absorption_power",
            name="Max Absorption Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_rated_battery_capacity",
            name="Rated Battery Capacity",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_rated_charge_power",
            name="ESS Rated Charge Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_rated_discharge_power",
            name="ESS Rated Discharge Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_daily_charge_energy",
            name="Daily Charge Energy",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            icon="mdi:battery-positive",
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_accumulated_charge_energy",
            name="Total Charge Energy",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            icon="mdi:battery-positive",
            suggested_unit_of_measurement=UnitOfEnergy.MEGA_WATT_HOUR
),
        SigenergySensorEntityDescription(
            key="inverter_ess_daily_discharge_energy",
            name="Daily Discharge Energy",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            icon="mdi:battery-negative",
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_accumulated_discharge_energy",
            name="Total Discharge Energy",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            icon="mdi:battery-negative",
            suggested_unit_of_measurement=UnitOfEnergy.MEGA_WATT_HOUR
        ),
        SigenergySensorEntityDescription(
            key="inverter_running_state",
            name="Running State",
            icon="mdi:power",
        ),
        SigenergySensorEntityDescription(
            key="inverter_max_active_power_adjustment_value",
            name="Max Active Power Adjustment",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_min_active_power_adjustment_value",
            name="Min Active Power Adjustment",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_max_reactive_power_adjustment_value_fed",
            name="Max Reactive Power Fed",
            native_unit_of_measurement="kvar",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_max_reactive_power_adjustment_value_absorbed",
            name="Max Reactive Power Absorbed",
            native_unit_of_measurement="kvar",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_active_power",
            name="Active Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            suggested_display_precision=3,
            icon="mdi:power-plug",
        ),
        SigenergySensorEntityDescription(
            key="inverter_reactive_power",
            name="Reactive Power",
            native_unit_of_measurement="kvar",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_charge_discharge_power",
            name="Battery Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:battery-charging-100",
            suggested_display_precision=3,
        ),
        # Battery power metrics
        SigenergySensorEntityDescription(
            key="inverter_ess_max_battery_charge_power",
            name="Max Battery Charge Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_max_battery_discharge_power",
            name="Max Battery Discharge Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_available_battery_charge_energy",
            name="Available Battery Charge Energy",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_available_battery_discharge_energy",
            name="Available Battery Discharge Energy",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_battery_soc",
            name="Battery State of Charge",
            device_class=SensorDeviceClass.BATTERY,
            native_unit_of_measurement=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:battery",
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_battery_soh",
            name="Battery State of Health",
            native_unit_of_measurement=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:battery-heart",
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_average_cell_temperature",
            name="Battery Average Cell Temperature",
            device_class=SensorDeviceClass.TEMPERATURE,
            native_unit_of_measurement=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:thermometer",
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_average_cell_voltage",
            name="Battery Average Cell Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_maximum_battery_temperature",
            name="Battery Maximum Temperature",
            device_class=SensorDeviceClass.TEMPERATURE,
            native_unit_of_measurement=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_minimum_battery_temperature",
            name="Battery Minimum Temperature",
            device_class=SensorDeviceClass.TEMPERATURE,
            native_unit_of_measurement=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_maximum_battery_cell_voltage",
            name="Battery Maximum Cell Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ess_minimum_battery_cell_voltage",
            name="Battery Minimum Cell Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Alarm registers
        SigenergySensorEntityDescription(
            key="inverter_alarm1",
            name="Alarm 1",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="inverter_alarm2",
            name="Alarm 2",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="inverter_alarm3",
            name="Alarm 3",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="inverter_alarm4",
            name="Alarm 4",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="inverter_alarm5",
            name="Alarm 5",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="inverter_grid_frequency",
            name="Grid Frequency",
            device_class=SensorDeviceClass.FREQUENCY,
            native_unit_of_measurement=UnitOfFrequency.HERTZ,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_pcs_internal_temperature",
            name="PCS Internal Temperature",
            device_class=SensorDeviceClass.TEMPERATURE,
            native_unit_of_measurement=UnitOfTemperature.CELSIUS,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:thermometer",
        ),
        SigenergySensorEntityDescription(
            key="inverter_output_type",
            name="Output Type",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Grid metrics
        SigenergySensorEntityDescription(
            key="inverter_rated_grid_voltage",
            name="Rated Grid Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_rated_grid_frequency",
            name="Rated Grid Frequency",
            device_class=SensorDeviceClass.FREQUENCY,
            native_unit_of_measurement=UnitOfFrequency.HERTZ,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Line voltages
        SigenergySensorEntityDescription(
            key="inverter_ab_line_voltage",
            name="A-B Line Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_bc_line_voltage",
            name="B-C Line Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_ca_line_voltage",
            name="C-A Line Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_phase_a_voltage",
            name="Phase A Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_phase_b_voltage",
            name="Phase B Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_phase_c_voltage",
            name="Phase C Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_phase_a_current",
            name="Phase A Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_phase_b_current",
            name="Phase B Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_phase_c_current",
            name="Phase C Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_power_factor",
            name="Power Factor",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # PV system metrics
        SigenergySensorEntityDescription(
            key="inverter_pack_count",
            name="PACK Count",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_pv_string_count",
            name="PV String Count",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_mppt_count",
            name="MPPT Count",
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="inverter_pv_power",
            name="PV Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:solar-power",

        ),
        SigenergySensorEntityDescription(
            key="inverter_insulation_resistance",
            name="Insulation Resistance",
            native_unit_of_measurement="MΩ",
            state_class=SensorStateClass.MEASUREMENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # This sensors are unkonown in what they do. The import kind of follows the PV production but it's a bit higher and begins earlier.
        # They are undocumented.
        # SigenergySensorEntityDescription(
        #     key="accumulated_export_energy",
        #     name="Accumulated Export Energy",
        #     device_class=SensorDeviceClass.ENERGY,
        #     native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        #     suggested_display_precision=2,
        #     state_class=SensorStateClass.TOTAL,
        # ),
        # SigenergySensorEntityDescription(
        #     key="accumulated_import_energy",
        #     name="Accumulated Import Energy",
        #     device_class=SensorDeviceClass.ENERGY,
        #     native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        #     suggested_display_precision=2,
        #     state_class=SensorStateClass.TOTAL,
        # ),
        # SigenergySensorEntityDescription(
        #     key="daily_export_energy",
        #     name="Daily Export Energy",
        #     device_class=SensorDeviceClass.ENERGY,
        #     native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        #     suggested_display_precision=2,
        #     state_class=SensorStateClass.TOTAL_INCREASING,
        # ),
        # SigenergySensorEntityDescription(
        #     key="daily_import_energy",
        #     name="Daily Import Energy",
        #     device_class=SensorDeviceClass.ENERGY,
        #     native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        #     suggested_display_precision=2,
        #     state_class=SensorStateClass.TOTAL_INCREASING,
        # ),

    ]
    AC_CHARGER_SENSORS = [
        SigenergySensorEntityDescription(
            key="ac_charger_system_state",
            name="System State",
            entity_category=EntityCategory.DIAGNOSTIC,
            icon="mdi:lightning-bolt-circle",
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_total_energy_consumed",
            name="Total Energy Consumed",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL_INCREASING,
            icon="mdi:car-electric",
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_charging_power",
            name="Charging Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:ev-plug-type2",
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_rated_power",
            name="Rated Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_rated_current",
            name="Rated Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_rated_voltage",
            name="Rated Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Additional AC charger metrics
        SigenergySensorEntityDescription(
            key="ac_charger_input_breaker_rated_current",
            name="Input Breaker Rated Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            entity_category=EntityCategory.DIAGNOSTIC,
            entity_registry_enabled_default=False,
        ),
        # Alarm registers
        SigenergySensorEntityDescription(
            key="ac_charger_alarm1",
            name="Alarm 1",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_alarm2",
            name="Alarm 2",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
        SigenergySensorEntityDescription(
            key="ac_charger_alarm3",
            name="Alarm 3",
            icon="mdi:alert",
            entity_category=EntityCategory.DIAGNOSTIC,
        ),
    ]

    DC_CHARGER_SENSORS = [
        SigenergySensorEntityDescription(
            key="dc_charger_vehicle_battery_voltage",
            name="DC Charger Vehicle Battery Voltage",
            device_class=SensorDeviceClass.VOLTAGE,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:car-battery",
        ),
        SigenergySensorEntityDescription(
            key="dc_charger_charging_current",
            name="DC Charger Charging Current",
            device_class=SensorDeviceClass.CURRENT,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:car-electric",
        ),
        SigenergySensorEntityDescription(
            key="dc_charger_output_power",
            name="DC Charger Output Power",
            device_class=SensorDeviceClass.POWER,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:ev-plug-ccs2",
        ),
        SigenergySensorEntityDescription(
            key="dc_charger_vehicle_soc",
            name="DC Charger Vehicle SOC",
            device_class=SensorDeviceClass.BATTERY,
            native_unit_of_measurement=PERCENTAGE,
            state_class=SensorStateClass.MEASUREMENT,
            icon="mdi:battery",
        ),
        SigenergySensorEntityDescription(
            key="dc_charger_current_charging_capacity",
            name="DC Charger Current Charging Capacity (Single Time)",
            device_class=SensorDeviceClass.ENERGY,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
            state_class=SensorStateClass.TOTAL,
            icon="mdi:car-electric",
        ),
        SigenergySensorEntityDescription(
            key="dc_charger_current_charging_duration",
            name="DC Charger Current Charging Duration (Single Time)",
            icon="mdi:timer",
            state_class=SensorStateClass.MEASUREMENT,
        ),
    ]


COORDINATOR_DIAGNOSTIC_SENSORS: tuple[SigenergySensorEntityDescription, ...] = (
    SigenergySensorEntityDescription(
        key="modbus_max_data_fetch_time",
        name="Modbus Max Data Fetch Time Since Restart",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sync-outline",
        suggested_display_precision=3,
    ),
    # Latest Fetch Time Sensors
    SigenergySensorEntityDescription(
        key="modbus_latest_fetch_time_high",
        name="Modbus HIGH Frequency Fetch Time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sync-outline",
        suggested_display_precision=3,
        entity_registry_enabled_default=False,
    ),
    SigenergySensorEntityDescription(
        key="modbus_latest_fetch_time_medium",
        name="Modbus MEDIUM Frequency Fetch Time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sync-outline",
        suggested_display_precision=3,
        entity_registry_enabled_default=False,
    ),
    SigenergySensorEntityDescription(
        key="modbus_latest_fetch_time_low",
        name="Modbus Low Frequency Fetch Time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sync-outline",
        suggested_display_precision=3,
        entity_registry_enabled_default=False,
    ),
    SigenergySensorEntityDescription(
        key="modbus_latest_fetch_time_alarm",
        name="Modbus ALARM Frequency Fetch Time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sync-outline",
        suggested_display_precision=3,
        entity_registry_enabled_default=False,
    ),
)
